name = "Modified Casper Two"
license = "MIT"
licenselink = "https://github.com/eueung/hugo-casper-two/blob/master/LICENSE.md"
description = "Fork of Casper 2.x from Ghost Foundation"
homepage = "https://github.com/sarahlshowers/hugo-casper-two.git"
tags = ["blog","pages","ghost theme"]
features = ["disqus", "google analytics"]
min_version=0.31

[author]
  name = "Sarah Showers"
  homepage = "https://www.sarahlshowers.com/"

[original]
  name = "Casper"
  homepage = "https://github.com/TryGhost/Casper"
  repo = "https://github.com/TryGhost/Casper"
